[project]
name = "qc-mnist-classification"
version = "0.1.0"
description = "a Quantum Computing approach to MNIST digit classification using PyTorch, TorchVision, and PennyLane"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
